packages:
  - packages/*
  - "!**/test/**"
saveExact: true
unsafePerm: true
enablePrePostScripts: true
autoInstallPeers: true
ignoreWorkspaceRootCheck: true
allowBuilds:
  "@kmamal/sdl": true
  canvas: true
  esbuild: true
  sharp: true
  typeslayer: true
