name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x', '20.x']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm --filter objecs lint

      - name: Build
        run: pnpm --filter objecs build

      - name: Test
        run: pnpm --filter objecs test --run
