name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["18.x", "20.x", "22.x"]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.5.2

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm --filter objecs lint

      - name: Build
        run: pnpm --filter objecs build

      - name: Check Exports
        run: pnpm --filter objecs check-exports

      - name: Test
        run: pnpm --filter objecs test -- --run
